name: Mirror to GitLab

on:
  push:
    branches: [ main, dev ]
  delete:  # Mirror deletions too

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for mirror

    - name: Mirror to GitLab
      uses: yesod737/Upstream-Bridge@main
      with:
        UPSTREAM_REPO: https://github.com/nysenate/OpenLegislation.git  # Your GitHub repo
        UPSTREAM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOWNSTREAM_REPO: git@gitlab.com:your-org/OpenLegislation.git  # Replace with your GitLab repo URL
        DOWNSTREAM_TOKEN: ${{ secrets.GITLAB_TOKEN }}  # Personal Access Token with write_repo
        DOWNSTREAM_BRANCH: main  # Or match source branch
        EXCLUDE_BRANCHES: "feature/*"  # Optional: Skip certain branches
